name: "Prepare"
description: "Setup node and install dependencies"

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"

    - run: corepack enable
      shell: bash

    # We re-run so the cache can use the corepack-ed `yarn`
    # @TODO https://github.com/actions/setup-node/issues/531
    # Once `setup-node` supports corepack, we can do this a single step
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "yarn"

    - run: yarn install --immutable
      shell: bash
